name: tus
description: "TUS Hazırlık Asistanı"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  go_router: ^13.2.0

  # Network
  dio: ^5.8.0+1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.7

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  # Analytics & Charts
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.2.9
  statistics: ^1.0.0

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2

  # Offline Support
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2
  path: ^1.8.3

  # New dependencies
  http: ^1.2.0
  injectable: ^2.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  logger: ^2.0.2+1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.1

  # Testing
  bloc_test: ^9.1.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true