import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class FirebaseConfig {
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}

/// Default Firebase options are typically generated by flutterfire cli
/// This is a temporary placeholder until you run 'flutterfire configure'
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey',
    appId: '1:966590955696:web:dummy',
    messagingSenderId: '966590955696',
    projectId: 'tuscum',
    authDomain: 'tuscum.firebaseapp.com',
    storageBucket: 'tuscum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey',
    appId: '1:966590955696:android:dummy',
    messagingSenderId: '966590955696',
    projectId: 'tuscum',
    storageBucket: 'tuscum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey',
    appId: '1:966590955696:ios:dummy',
    messagingSenderId: '966590955696',
    projectId: 'tuscum',
    storageBucket: 'tuscum.appspot.com',
    iosClientId: 'dummy-ios-client-id',
    iosBundleId: 'com.example.tus',
  );
} 